-- MySQL Script generated by MySQL Workbench
-- Mon Feb 21 17:21:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_tema` (
  `id` BIGINT NOT NULL,
  `descrição` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagem` (
  `id` BIGINT NOT NULL,
  `tb_postagem_idtb_postagem` BIGINT NOT NULL,
  `tb_tema_idtable1` BIGINT NOT NULL,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bd_BlogPessoal_tb_postagem_idx` (`tb_postagem_idtb_postagem` ASC) VISIBLE,
  INDEX `fk_bd_BlogPessoal_tb_tema1_idx` (`tb_tema_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_bd_BlogPessoal_tb_postagem`
    FOREIGN KEY (`tb_postagem_idtb_postagem`)
    REFERENCES `mydb`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bd_BlogPessoal_tb_tema1`
    FOREIGN KEY (`tb_tema_idtable1`)
    REFERENCES `mydb`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
